### ISSUE TITLE
It doesn't register(insert all req fields) or send mail

### ISSUE THREAD

**Issue by sayopaul** [nurazije/phpSecureLogin#1]
When i tried registering, it doesn't register and brings an alert box with a "Insert all valid required fields error". To get the registeration to work, I had to comment out this if statement

```
/* if(!(isset($email) && isset($fname) && isset($lname) && isset($pass) && filter_var($email, FILTER_VALIDATE_EMAIL))){
$this->msg = 'Insert all valid required fields.';
return false;
}*/
```
and then it worked. But it won't send the mail. I think its probably because the php mail() function won't work on most localhosts . Maybe you could use phpmailer instead for that. Well done !!

**Comment by nurazije** [comment]
thank you for the advice 👍
